#pragma once
#include "VectorEngineSimpleMatrixOperationsAdditionTest.h"
#include "VectorEngineSimpleMatrixOperationsSubstractionTest.h"
#include "VectorEngineSimpleMatrixOperationsMultiplicationTest.h"
#include "VectorEngineSimpleMatrixOperationsHadamardTest.h"
#include "VectorEngineSimpleMatrixOperationsInverseTest.h"
#include "VectorEngineSimpleMatrixOperationsDeterminantTest.h"