#pragma once

#include "VectorEngineTypeMatrixBasisTest.h"
#include "VectorEngineTypeMatrixCheckSpanTest.h"
#include "VectorEngineTypeMatrixDependentTest.h"
#include "VectorEngineTypeMatrixFullRankTest.h"
#include "VectorEngineTypeMatrixHomogeneousTest.h"
#include "VectorEngineTypeMatrixIsEqualTest.h"
#include "VectorEngineTypeMatrixIsFullDependentTest.h"
#include "VectorEngineTypeMatrixIsInSpanTest.h"
#include "VectorEngineTypeMatrixIsSameSizeTest.h"
#include "VectorEngineTypeMatrixIsSquareTest.h"
#include "VectorEngineTypeMatrixIsZeroMatrixTest.h"
#include "VectorEngineTypeMatrixOrthogonalTest.h"
#include "VectorEngineTypeMatrixRankTest.h"
#include "VectorEngineTypeMatrixSpanTest.h"
#include "VectorEngineTypeMatrixTrivialTest.h"